[project]
name = "python-htmlelements"
version = "0.3.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[project.optional-dependencies]
django = ["django>=5.2.0"]
